# 站点基础配置
url: "https://gyung.github.io"
baseurl: ""
lang: zh-CN
locale: zh_CN
timezone: Asia/Shanghai

# 标题与描述
title: "GYung 的博客"
description: "记录学习、开发与生活碎片"
author:
  name: "GYung"
  email: ""
  url: "https://gyung.github.io"

# Beautiful Jekyll 主题配置
# 主题：https://github.com/daattali/beautiful-jekyll

# 站点信息
title: "GYung 的技术博客"
description: "分享前端开发、全栈技术、效率工具与学习心得"
author: "GYung"
avatar-img: "https://avatars.githubusercontent.com/GYung"
email: ""
url: "https://gyung.github.io"
baseurl: ""

# 社交链接
social-network-links:
  github: GYung
  twitter: ""
  facebook: ""
  linkedin: ""
  xing: ""
  instagram: ""
  youtube: ""
  snapchat: ""
  googlescholar: ""
  orcid: ""
  researchgate: ""
  email: ""

# 导航链接
navbar-links:
  关于: "about"
  分类: "categories"
  标签: "tags"
  归档: "archive"

# 侧边栏配置
sidebar-about-description: "前端开发工程师，专注于现代 Web 技术栈。热爱分享技术心得，记录学习成长。"
sidebar-avatar: "https://avatars.githubusercontent.com/GYung"

# 评论系统 (可选)
comments:
  provider: disqus
  disqus:
    shortname: ""

# 分析工具 (可选)
analytics:
  provider: google
  google:
    tracking_id: ""

# 其他设置
lang: zh-CN
locale: zh_CN
timezone: Asia/Shanghai

# Beautiful Jekyll 会自动处理导航

# 插件（GitHub Pages 支持）
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Markdown 与语法高亮
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge

# 默认 Front Matter
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "GYung"
      comments: false

# 排除不需要构建的文件
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .github
  - README.md
